# Generated by Django 4.2 on 2025-01-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_activation_key_user_activation_key_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_created',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 13, 3, 43, 412224, tzinfo=datetime.timezone.utc)),
        ),
    ]
