# Generated by Django 4.2 on 2025-01-24 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_activation_key_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 26, 11, 20, 12, 520633, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
