# Generated by Django 4.2 on 2025-01-31 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 2, 6, 40, 30, 898314, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
